### ISSUE TITLE
issues with bicep - document-intelligence.bicep - roleDefinitionId

### ISSUE THREAD

**Issue by fepere** [jamesmcroft/azure-document-intelligence-markdown-to-openai-data-extraction-sample#1]
Hello James,

I'm trying to deploy this code on my subscription but it's failing with few errors., can you please help me?

Your CLI is up-to-date.
WARNING: C:\Users\fpereira\Downloads\azure-document-intelligence-markdown-to-openai-data-extraction-sample\infra\ai_ml\document-intelligence.bicep(59,5) : Warning use-resource-id-functions: If property "roleDefinitionId" represents a resource ID, it must use a symbolic resource reference, be a parameter or start with one of these functions: extensionResourceId, guid, if, reference, resourceId, subscription, subscriptionResourceId, tenantResourceId. [https://aka.ms/bicep/linter/use-resource-id-functions]

ERROR: {"code": "InvalidTemplateDeployment", "message": "The template deployment 'docintel-gpt-document-extraction' is not valid according to the validation procedure. The tracking id is '1cc69584-5087-4e64-b27b-b221b85dc83e'. See inner errors for details."}

Inner Errors:
{"code": "SpecialFeatureOrQuotaIdRequired", "message": "The subscription does not have QuotaId/Feature required by SKU 'S0' from kind 'OpenAI' or contains blocked QuotaId/Feature."}
ERROR: argument --name/-n: expected one argument

Examples from AI knowledge base:
az cognitiveservices account keys list --name myresource --resource-group cognitive-services-resource-group
Get current resource keys.

https://docs.microsoft.com/en-US/cli/azure/cognitiveservices/account/keys#az_cognitiveservices_account_keys_list
Read more about the command in reference docs
ERROR: argument --name/-n: expected one argument

Examples from AI knowledge base:
az cognitiveservices account keys list --name myresource --resource-group cognitive-services-resource-group
Get current resource keys.

https://docs.microsoft.com/en-US/cli/azure/cognitiveservices/account/keys#az_cognitiveservices_account_keys_list
Read more about the command in reference docs
Saving the deployment outputs to a config.env file...

    Directory: C:\Users\fpereira\Downloads\azure-document-intelligence-markdown-to-openai-data-extraction-sample

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           4/27/2024 10:10 PM              0 config.env

PS C:\Users\fpereira\Downloads\azure-document-intelligence-markdown-to-openai-data-extraction-sample>

I try to run on sample.ipynb and get this output

Your CLI is up-to-date.
WARNING: [C:\Users\fpereira\Downloads\azure-document-intelligence-markdown-to-openai-data-extraction-sample\infra\ai_ml\document-intelligence.bicep](file:///C:/Users/fpereira/Downloads/azure-document-intelligence-markdown-to-openai-data-extraction-sample/infra/ai_ml/document-intelligence.bicep)(59,5) : Warning use-resource-id-functions: If property "roleDefinitionId" represents a resource ID, it must use a symbolic resource reference, be a parameter or start with one of these functions: extensionResourceId, guid, if, reference, resourceId, subscription, subscriptionResourceId, tenantResourceId. [https://aka.ms/bicep/linter/use-resource-id-functions]

...

https://docs.microsoft.com/en-US/cli/azure/cognitiveservices/account/keys#az_cognitiveservices_account_keys_list
Read more about the command in reference docs
Saving the deployment outputs to a config.env file...

**Comment by jamesmcroft** [comment]
@fepere can you confirm that you have registered for access to Azure OpenAI?

If not, there is a [registration form](https://learn.microsoft.com/en-us/legal/cognitive-services/openai/limited-access#registration-process) you can fill in which will enable this service for deployment in your Azure subscription.

**Comment by fepere** [comment]
Hi @jamesmcroft ,

Yes, you are right, I might that was already allowed, but was not. I made the request and now was able to deploy the code.

if you can add this disclaimer would be great as well.

Thank you for helping me out.
FP

**Comment by jamesmcroft** [comment]
@fepere not a problem at all, and apologies for missing this information in the sample. 

I have updated the Sample notebook pre-requisites and the README to call out this requirement.
